export { default as categoriesSlice } from "./categoriesSlice";
export { default as brandsSlice } from "./brandsSlice";
export { default as productsSlice } from "./productsSlice";
export { default as newProductsSlice } from "./newProductsSlice";
export { default as stylesSlice } from "./stylesSlice";
export { default as sortSlice } from "./sortSlice";
export { default as filtersSlice } from "./filter";
export { default as colorsSlice } from "./colorsSlice";
export { default as sizesSlice } from "./sizesSlice";
export { default as productDetailSlice } from "./productDetailSlice";
export { default as quantitySlice } from "./quantitySlice";
export { default as authSlice } from "./authSlice";

export * from "./categoriesSlice";
export * from "./brandsSlice";
export * from "./productsSlice";
export * from "./newProductsSlice";
export * from "./stylesSlice";
export * from "./sortSlice";
export * from "./filter";
export * from "./colorsSlice";
export * from "./sizesSlice";
export * from "./productDetailSlice";
export * from "./quantitySlice";
export * from "./authSlice";
