export {default as categoriesSlice} from './categoriesSlice'
export {default as brandsSlice} from './brandsSlice'
export {default as productsSlice} from './productsSlice'
export {default as stylesSlice} from './stylesSlice'
export {default as sortSlice} from './sortSlice'
export {default as filtersSlice} from './filter'

export * from './categoriesSlice'
export * from './brandsSlice'
export * from './productsSlice'
export * from './stylesSlice'
export * from './sortSlice'
export * from './filter'